config/routes.rb
Rails.application.routes.draw do
  resources :lecturers

  get 'link/index'

  get 'link/course'

  get 'link/lecturer'

  get 'link/about'
  
  get 'link/members'
  
  get 'link/requirements'
  
  get 'link/features'
  
  get 'link/er_diagram'
  
  get 'link/lo_fimockup'
  
  get 'courses/index', :to => 'courses#index', :as => 'courses_index' 
  
  get 'lecturers/index', :to => 'lecturers#index', :as => 'lecturer_index'
  

  resources :courses

  root to: 'link#index'
  
end

app/models/course.rb
class Course < ActiveRecord::Base
    validates :course, :coursename, :lecturer, :semester, :year, presence: true
    validates :course, uniqueness: true
end

app/models/lecturer.rb
class Lecturer < ActiveRecord::Base
    validates :identificationnumber, :name, presence: true
    validates :identificationnumber, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
    @courses = Course.all
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new}
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy 
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:course, :coursename, :lecturer, :semester, :year, :room, :examdate)
    end
end

app/controllers/lecturers_controller.rb
class LecturersController < ApplicationController
  before_action :set_lecturer, only: [:show, :edit, :update, :destroy]

  # GET /lecturers
  # GET /lecturers.json
  def index
    @lecturers = Lecturer.all
  end

  # GET /lecturers/1
  # GET /lecturers/1.json
  def show
  end

  # GET /lecturers/new
  def new
    @lecturer = Lecturer.new
  end

  # GET /lecturers/1/edit
  def edit
  end

  # POST /lecturers
  # POST /lecturers.json
  def create
    @lecturer = Lecturer.new(lecturer_params)

    respond_to do |format|
      if @lecturer.save
        format.html { redirect_to @lecturer, notice: 'Lecturer was successfully created.' }
        format.json { render :show, status: :created, location: @lecturer }
      else
        format.html { render :new }
        format.json { render json: @lecturer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lecturers/1
  # PATCH/PUT /lecturers/1.json
  def update
    respond_to do |format|
      if @lecturer.update(lecturer_params)
        format.html { redirect_to @lecturer, notice: 'Lecturer was successfully updated.' }
        format.json { render :show, status: :ok, location: @lecturer }
      else
        format.html { render :edit }
        format.json { render json: @lecturer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lecturers/1
  # DELETE /lecturers/1.json
  def destroy
    @lecturer.destroy
    respond_to do |format|
      format.html { redirect_to lecturers_url, notice: 'Lecturer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lecturer
      @lecturer = Lecturer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lecturer_params
      params.require(:lecturer).permit(:identificationnumber, :name, :faculty, :department)
    end
end

app/controllers/link_controller.rb
class LinkController < ApplicationController
  def index
    @courses = Course.all
  end

  def course
  end

  def lecturer
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/lecturers_helper.rb
module LecturersHelper
end

app/helpers/link_helper.rb
module LinkHelper
end

app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <h2>Error:</h2>
    <ul>
      <% @course.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  
  <div class="field">
    <%= f.label :course %><br>
    <%= f.text_field :course,:placeholder => "CN320" %>
  </div>
  <div class="field">
    <%= f.label :coursename %><br>
    <%= f.text_field :coursename ,:placeholder => "Software Engineering" %>
  </div>
  <div class="field">
    <%= f.label :lecturer %><br>
    <%= f.text_field :lecturer,:placeholder => "Dr.Phisan Kaewprapa" %>
  </div>
  <div class="field">
    <%= f.label :semester %><br>
    <%= f.number_field :semester,:placeholder => "1" %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year,:placeholder => "2557" %>
  </div>
  <div class="field">
    <%= f.label :room %><br>
    <%= f.text_field :room,:placeholder => "ENGR-316" %>
  </div>
  <div class="field">
    <%= f.label :examdate %><br>
    <%= f.text_field :examdate,:placeholder => "20 พฤษภาคม 2558" %>
  </div>
  <div class="actions">
    <%= f.submit 'Submit' %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing course</h1>

<%= render 'form' %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<h1>Courses</h1>
<div class="media">
  <div class="media-body">
<table class="table table-hover">
  <thead>
    <tr>
      <th>Course</th>
      <th>Coursename</th>
      <th>Lecturer</th>
      <th>Semester</th>
      <th>Year</th>
      <th>Room</th>
      <th>Examdate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.course %></td>
        <td><%= course.coursename %></td>
        <td><%= course.lecturer %></td>
        <td><%= course.semester %></td>
        <td><%= course.year %></td>
        <td><%= course.room %></td>
        <td><%= course.examdate %></td>
        <td><%= link_to 'Show', course, class: 'btn btn-mini btn-warning' %></td>
        <td><%= link_to 'Edit', edit_course_path(course), class: 'btn btn-mini btn-success' %></td>
        <td><%= link_to 'Delete', course, method: :delete, class: 'btn btn-mini btn-danger', data: { confirm: 'Are you sure?' },:id => "#{course.course}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
  </div>
</div>
<br>

<%= link_to 'New Course', new_course_path %>

app/views/courses/new.html.erb
<h1>New course</h1>

<%= render 'form' %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Course:</strong>
  <%= @course.course %>
</p>

<p>
  <strong>Coursename:</strong>
  <%= @course.coursename %>
</p>

<p>
  <strong>Lecturer:</strong>
  <%= @course.lecturer %>
</p>

<p>
  <strong>Semester:</strong>
  <%= @course.semester %>
</p>

<p>
  <strong>Year:</strong>
  <%= @course.year %>
</p>

<p>
  <strong>Room:</strong>
  <%= @course.room %>
</p>

<p>
  <strong>Examdate:</strong>
  <%= @course.examdate %>
</p>


<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TermProject</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse">
  <div class="container-fluid">
   

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Course", courses_path %></li>
        <li><%= link_to "Lecturer", lecturers_path %></li>
        <li class="ABOUT">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">About<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            
            <li><%= link_to "Members", link_members_path %></li>
            <li class="divider"></li>
            <li><%= link_to "Requirements", link_requirements_path %></li>
            <li class="divider"></li>
            <li><%= link_to "Features", link_features_path %></li>
            <li class="divider"></li>
            <li><%= link_to "ER-Diagram", link_er_diagram_path %></li>
            <li class="divider"></li>
            <li><%= link_to "Lo-Fi Mockup & Storyboards", link_lo_fimockup_path %></li>
            <li class="divider"></li>
          </ul>
        </li>
      </ul>
      
    </div>
  </div>
</nav>


  
  

  <%= yield %>


</body>
</html>

app/views/lecturers/_form.html.erb
<%= form_for(@lecturer) do |f| %>
  <% if @lecturer.errors.any? %>
    <h2>Error:</h2>
    <ul>
      <% @lecturer.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  <div class="field">
    <%= f.label :identificationnumber %><br>
    <%= f.number_field :identificationnumber,:placeholder => "1" %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name,:placeholder => "Dr.Phisan Kaewprapa" %>
  </div>
  <div class="field">
    <%= f.label :faculty %><br>
    <%= f.text_field :faculty,:placeholder => "Engineering" %>
  </div>
  <div class="field">
    <%= f.label :department %><br>
    <%= f.text_field :department,:placeholder => "Computer" %>
  </div>
  <div class="actions">
    <%= f.submit 'Submit' %>
  </div>
<% end %>

app/views/lecturers/edit.html.erb
<h1>Editing lecturer</h1>

<%= render 'form' %>


<%= link_to 'Show', @lecturer %> |
<%= link_to 'Back', lecturers_path %>

app/views/lecturers/index.html.erb
<h1>Lecturers</h1>

<div class="media">
  <div class="media-body">
<table class="table table-hover">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Faculty</th>
      <th>Department</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lecturers.each do |lecturer| %>
      <tr>
        <td><%= lecturer.identificationnumber %></td>
        <td><%= lecturer.name %></td>
        <td><%= lecturer.faculty %></td>
        <td><%= lecturer.department %></td>
        <td><%= link_to 'Show', lecturer, class: 'btn btn-mini btn-warning' %></td>
        <td><%= link_to 'Edit', edit_lecturer_path(lecturer), class: 'btn btn-mini btn-success' %></td>
        <td><%= link_to 'Delete', lecturer, method: :delete , class: 'btn btn-mini btn-danger', data: { confirm: 'Are you sure?' },:id => "#{lecturer.name}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
  </div>
</div>
<br>

<%= link_to 'New Lecturer', new_lecturer_path %>

app/views/lecturers/new.html.erb
<h1>New lecturer</h1>

<%= render 'form' %>

<%= link_to 'Back', lecturers_path %>

app/views/lecturers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Identificationnumber:</strong>
  <%= @lecturer.identificationnumber %>
</p>

<p>
  <strong>Name:</strong>
  <%= @lecturer.name %>
</p>

<p>
  <strong>Faculty:</strong>
  <%= @lecturer.faculty %>
</p>

<p>
  <strong>Department:</strong>
  <%= @lecturer.department %>
</p>


<%= link_to 'Edit', edit_lecturer_path(@lecturer) %> |
<%= link_to 'Back', lecturers_path %>

app/views/link/about.html.erb
<h1>ABOUT</h1> 


<h2>Members</h2>
<table>
  <tbody>
    <tr>
      <td>Jetsada</td>
      <td>Yotawong</td>
      <td>5510520173</td>
    </tr>
    <tr>
      <td>Puttiwat</td>
      <td>Poonupa</td>
      <td>5510520199</td>
    </tr>
    <tr>
      <td>Satapana</td>
      <td>Intaraporm</td>
      <td>5510613200</td>
    </tr>
    <tr>
      <td>Chanatip</td>
      <td>Thongaunruan</td>
      <td>5510613341</td>
    </tr>
    <tr>
      <td>Phuwanart</td>
      <td>Chotikanjana</td>
      <td>5510613374</td>
    </tr>
    <tr>
      <td>Korrakod</td>
      <td>Maikate</td>
      <td>5510613465</td>
    </tr>
  </tbody>
</table>
<h2>Requirements</h2>
ต้องเพิ่มรายวิชาได้
<br>
  ต้องลบรายวิชาได้
  <br>
    ต้องจัดการ/แก้ไขข้อมูลรายวิชาได้
    <br>
      ต้องเพิ่มข้อมูลอาจารย์ผู้สอนได้
      <br>
        ต้องลบข้อมูลอาจารย์ผู้สอนได้
        <br>
          ต้องจัดการ/แก้ไขข้อมูลอาจารย์ผู้สอนได้
          <br>
            ข้อมูลรายวิชามี รหัสวิชา ชื่อวิชา ชื่ออาจารย์ที่สอน ภาคเรียนที่เท่าไร ปีการศึกษาใด วัน-เวลาที่สอบ
            <br>
              ข้อมูลอาจารย์ผู้สอนต้องมี ชื่ออาจารย์ คณะใด ภาควิชาใด
              <br>
                สามารถแสดงข้อมูลการเรียนเป็นตารางโดยมีวิชาและห้องเรียน
</br>
<div>
  <h2>Features</h2>
  <ol>
    <li>
      As a registrar staff
      <br/>
      I want to add a lecturer to Course Management database
    </li>
    <li>
      As a registrar staff
      <br/>
      I want to edit a lecturer from Course Management database
    </li>
    <li>
      As a registrar staff
      <br/>
      I want to remove a lecturer from Course Management database
    </li>
    <li>
      As a registrar staff
      <br/>
      I want to add a course to Course Management database
    </li>
    <li>
      As a registrar staff
      <br/>
      I want to edit a course from Course Management database
    </li>
    <li>
      As a registrar staff
      <br/>
      I want to remove a course from Course Management database
    </li>
  </ol>
</div>
<div>
  <h1>ER-Diagram</h1>
  
  <img src="/assets/ER-V1.JPG" width="971" height="366" alt="Edit Entry" />
</div>
<div>
  <%= link_to "Pivotal Tracker", "https://www.pivotaltracker.com/n/projects/1300664" %>
  <%= link_to "Github", "https://github.com/kaitookita/term-project" %>
</div>
<div>
  <h1>Lo-fi Mockups & Storyboards</h1>
  <img src="/assets/Storyboard.jpg" width="960" height="540" alt="Edit Entry" />
</div>
<%= link_to 'Back', root_path %>

app/views/link/course.html.erb
<h1>Link#course</h1>
<p>Find me in app/views/link/course.html.erb</p>

app/views/link/er_diagram.html.erb
<div>
  <h1>ER-Diagram</h1>
  
  <img src="/assets/ER-V1.JPG" width="971" height="366" alt="Edit Entry" />
</div>
<div>
  <%= link_to "Pivotal Tracker", "https://www.pivotaltracker.com/n/projects/1300664" %>
  <%= link_to "Github", "https://github.com/kaitookita/term-project" %>
</div>

app/views/link/features.html.erb
<div>
  <h2>Features</h2>
  <ol>
    <li>
      As a registrar staff
      <br/>
      I want to add a lecturer to Course Management database
    </li>
    <li>
      As a registrar staff
      <br/>
      I want to edit a lecturer from Course Management database
    </li>
    <li>
      As a registrar staff
      <br/>
      I want to remove a lecturer from Course Management database
    </li>
    <li>
      As a registrar staff
      <br/>
      I want to add a course to Course Management database
    </li>
    <li>
      As a registrar staff
      <br/>
      I want to edit a course from Course Management database
    </li>
    <li>
      As a registrar staff
      <br/>
      I want to remove a course from Course Management database
    </li>
  </ol>
</div>
<div>

app/views/link/index.html.erb
<h1>Course Management</h1>

<div class="media">
  <div class="media-body">
<table class="table table-hover">
  <thead>
    <tr>
      <th>Courses</th>
      <th>Coursename</th>
      
      <th>Lecturer</th>
      <th>Semester</th>
      <th>Year</th>
      <th colspan="3"></th>

    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.course %></td>
        <td><%= course.coursename %></td>
       
        <td><%= course.lecturer %></td>
        <td><%= course.semester %></td>
        <td><%= course.year %></td>
       
    <% end %>
   
  </tbody>
</table>
  </div>
</div>
<br>

app/views/link/lecturer.html.erb
<h1>Link#lecturer</h1>
<p>Find me in app/views/link/lecturer.html.erb</p>

app/views/link/lo_fimockup.html.erb
<div>
  <h1>Lo-fi Mockups & Storyboards</h1>
  <img src="/assets/Storyboard.jpg" width="960" height="540" alt="Edit Entry" />
</div>
<%= link_to 'Back', root_path %>

app/views/link/members.html.erb
<h2>Members</h2>


<table class="table table-striped table-hover ">
 
  <tbody>
   
    <tr>
      <td>1</td>
      <td>Jetsada</td>
      <td>Yotawong</td>
      <td>5510520173</td>
    </tr>
    
      <tr>
      <td>2</td>
      <td>Puttiwat</td>
      <td>Poonupa</td>
      <td>5510520199</td>
    </tr>
    
      <tr>
      <td>3</td>
      <td>Satapana</td>
      <td>Intaraporm</td>
      <td>5510613200</td>
    </tr>
    
      <tr>
      <td>4</td>
      <td>Chanatip</td>
      <td>Thongaunruan</td>
      <td>5510613341</td>
    </tr>
    
      <tr>
      <td>5</td>
      <td>Phuwanart</td>
      <td>Chotikanjana</td>
      <td>5510613374</td>
    </tr>
    
      <tr>
      <td>6</td>
      <td>Korrakod</td>
      <td>Maikate</td>
      <td>5510613465</td>
    </tr>
   
  </tbody>
</table> 

app/views/link/requirements.html.erb
<div>
  <ol>
<h2>Requirements</h2>
ต้องเพิ่มรายวิชาได้
<br>
  ต้องลบรายวิชาได้
  <br>
    ต้องจัดการ/แก้ไขข้อมูลรายวิชาได้
    <br>
      ต้องเพิ่มข้อมูลอาจารย์ผู้สอนได้
      <br>
        ต้องลบข้อมูลอาจารย์ผู้สอนได้
        <br>
          ต้องจัดการ/แก้ไขข้อมูลอาจารย์ผู้สอนได้
          <br>
            ข้อมูลรายวิชามี รหัสวิชา ชื่อวิชา ชื่ออาจารย์ที่สอน ภาคเรียนที่เท่าไร ปีการศึกษาใด วัน-เวลาที่สอบ
            <br>
              ข้อมูลอาจารย์ผู้สอนต้องมี ชื่ออาจารย์ คณะใด ภาควิชาใด
              <br>
                สามารถแสดงข้อมูลการเรียนเป็นตารางโดยมีวิชาและห้องเรียน
</br>
</ol>
</div>